### ISSUE TITLE
Visualization doesn't work for huge images

### ISSUE THREAD

**Issue by dvsorokin** [Borda/dataset-histology-landmarks#2]
It seems that `run_visualise_landmarks.py` doesn't work for big images:

```
"""
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "E:\CBIA\PROJECTS\ANHIR 2018\dataset-histology-landmarks-master\handlers\run_visualise_landmarks.py", line 84, in export_visual_set_scale
    np.array(Image.open(p_img)))
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2642, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2633, in _open_core
    _decompression_bomb_check(im.size)
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2568, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError: Image size (200383248 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

**Comment by Borda** [comment]
solved by using `matplotlib.pyplot.imread()`
